export const FETCH_SIGNALS_START = 'FETCH_SIGNALS_START'
export const FETCH_SIGNALS_SUCCESS = 'FETCH_SIGNALS_SUCCESS'
export const FETCH_SIGNALS_FAIL = 'FETCH_SIGNALS_FAIL'
export const FETCH_SIGNALS = 'FETCH_SIGNALS'
